/*
	file: 	letter.js
	desc: 	simple script that generates a (skeleton) letter
			based on Christopher Stratchey's Love Letter as 
			analysed by Noah Wardrip-Fruin in "Digital Media Archeology"
	author: Martin Roger Nkpwang Ze
	date: 	28/11/16
*/

// import chance (http://chancejs.com)
var chance = require('chance').Chance(); // npm install --save chance

// import word-wrap (https://www.npmjs.com/package/word-wrap)
var wrap = require('word-wrap'); // npm install --save word-wrap

// Stratchey's Love letter vocabulary database 
// based on Noah Wardrip-Fruin's "Digital Media Archeology" Table 14.1
const first = ['DARLING', 'DEAR', 'HONEY', 'JEWEL'];

const second = ['DUCK', 'LOVE', 'MOPPET', 'SWEETHEART'];

const adjectives = ['ENCHANTING', 'ATTRACTIVE', 'CAPTIVATING', 'ANXIOUS', 'CRAZY', 'BIGGER', 'CONSCIOUS', 'CONSIDEROUS', 'MEMORABLE', 'SOLITARY', 'CURIOUS', 'DISAPPOINTING', 'GRACIOUS', 'EARTHLY', 'EMOTIONAL', 'GORGIOUS', 'HEARTBREAKING', 'LITTLE', 'IRRATIONAL', 'PLAYFUL', 'LUSTFUL', 'PASSIONATE', 'PRECIOUS', 'SWEET', 'SYMPATHETIC', 'VENDICTIVE'];

const nouns = ['FANTASY', 'NIGHTMARE', 'DELIGHT', 'JOY', 'MARVEL', 'VISION', 'CHARACTER', 'SIN', 'MEMOMRY', 'CRAVINGS', 'LETHARGY','DELUSIONS', 'SYMPATHY','DRAGON', 'FAME', 'FORTUNE', 'TALE'];

const adverbs = ['MOURNFULLY', 'SPITEFULLY', 'BOLDLY', 'SUDDENLY', 'AUTOMATICALLY', 'NORMALLY',
'PRAGMATICALLY', 'ARGUMENTATIVELY', 'SHORTLY', 'WRONGLY', 'EFFORTLESSLY', 'PAINSTAKINGLY', 'BREATHLESSLY',
'PROUDLY', 'GREATLY', 'HORRIFYINGLY'];

const verbs = ['REMEMBERS', 'CONNECTS', 'ADORES', 'WISHES', 'MAKES', 'CARRIES', 'DREAMS', 'TENDS TO', 'CREATES',
              'COMMANDS', 'SERENADES','TAKES FOR GRANTED','REGRETS','FORGETS','SEES'];


/**
*	Picks a random element from an array
*	@param {Array} array
*	@return {Object} choice
*/
function choice(array) {
	var index = chance.natural({'min': 0, 'max': array.length - 1});
	return array[index];
}

/**
*	Randomly picks or not a random element from an array
*	@param {Array} array
*	@return {Object} choice 
* 	@return {String} empty string
*/
function maybe(array) {
	if( chance.bool() ) {
		return choice(array);
	} else {
		return '';
	}
}

/**
*	Generates a short phrase consisting of a randomly chosen 
*	adjective and noun
*	@return {String} phrase
*/
function short() {
	return choice(adjectives) + ' ' + choice(nouns);
}

/**
*	Generates a sentence composed of randomly chosen 
*	adjective, noun, adverb, verb, adjective and noun
*	@return {String} sentence
*/
function long() {
	return 'MY ' + maybe(adjectives) + ' ' + choice(nouns) + ' ' +
					maybe(adverbs) + ' ' + choice(verbs) + ' ' +
					'YOUR ' + maybe(adjectives) + ' ' + choice(nouns) + '. ';
}

// format the output (header)
console.log('\n\n\n\n'); 	// 4 x newline ('\n')

// in order to use word-wrap, I need to construct a single string
// (text) containing all generated sentences
var text = '';

// loop generating 5 sentences
for(var i = 0; i < 5; i++) {

	// concatenate the new sentence generated by long() with the text string
	text += long();	// (+=) text = text + long()
}

// wrap the text with a width of 65 characters and log (output) it to the console
console.log(wrap(text, {'width': 65}));

// format for the output (footer)
console.log('\n\n\n\n');	// 4 x newline ('\n')

